--P2 A
SELECT B.IDCUENTA "CUENTA_PROPIETARIA",
       B.USUARIO, A.DESCRIPCION "TIPO_CUENTA",
       COUNT(D.FLAGLIKE) "NUM_LIKES"
FROM TIPOCUENTA A, CUENTA B, VIDEO C, ACCION D
WHERE A.IDTIPOCUENTA=B.IDTIPOCUENTA AND
      B.IDCUENTA=C.IDCUENTA_PROPIETARIA AND
      C.IDVIDEO=D.IDVIDEO AND 
      TO_CHAR(D.FECHA_LIKE, 'DD-MONTH-YYYY') BETWEEN
        '01-AGOSTO-2021' AND '30-SETIEMBRE-2021'
GROUP BY B.IDCUENTA, B.USUARIO, A.DESCRIPCION
HAVING COUNT(D.FLAGLIKE)>10
ORDER BY 1 DESC;
/
--P2 B
SELECT ROWNUM, T.*
FROM (
    SELECT A.IDVIDEO, A.TITULO "VIDEO", 
           COUNT(B.FLAGCOMPARTIDO) "COMPARTIDO",
           SUM(B.MIN_REPRODUCCION) 
           "MINUTOS_REPRODUCCION"
    FROM VIDEO A, ACCION B
    WHERE A.IDVIDEO=B.IDVIDEO AND
          EXISTS (
            SELECT *
            FROM PUBLICIDAD_X_VIDEO X
            WHERE X.IDVIDEO=A.IDVIDEO AND X.ACTIVO=1
          )
    GROUP BY A.IDVIDEO, A.TITULO
    HAVING COUNT(B.FLAGCOMPARTIDO)>=3
    ORDER BY 4 DESC
) T
WHERE ROWNUM<=5
/
--P2 C
ALTER TABLE PUBLICIDAD ADD IDPUBLICIDAD_ASOCIADA NUMBER NULL;
/
ALTER TABLE PUBLICIDAD
--             nombre del fk
ADD CONSTRAINT IDPUBLICIDAD_ASOCIADA_FK
             --campo a convertir a fk          --tabla del pk campo pk que apunta el fk
FOREIGN KEY (IDPUBLICIDAD_ASOCIADA) REFERENCES PUBLICIDAD (IDPUBLICIDAD)
/
--actualizacion de filas
UPDATE PUBLICIDAD X
SET IDPUBLICIDAD_ASOCIADA = IDPUBLICIDAD+2
WHERE EXISTS
    (SELECT * 
     FROM PUBLICIDAD Y
     WHERE Y.IDPUBLICIDAD=X.IDPUBLICIDAD+2)
/
--P2 D
SELECT B.USUARIO "Cuenta propietaria",
       A.TITULO, B2.USUARIO, C.MIN_REPRODUCCION,
       TO_CHAR(C.FECHA_LIKE, 'DD "de" FMMonth "del" YYYY', 'NLS_DATE_LANGUAGE=SPANISH')
FROM VIDEO A, CUENTA B, CUENTA B2, ACCION C
WHERE A.IDCUENTA_PROPIETARIA=B.IDCUENTA AND
      B2.IDCUENTA=C.IDCUENTA AND
      A.IDVIDEO=C.IDVIDEO AND
      C.FLAGLIKE=1 AND
      B.IDCUENTA<>B2.IDCUENTA
ORDER BY 2, 3;
/
--P2 E
CREATE VIEW VISTA_PAGOS_POR_PUBLICIDAD AS
SELECT A.USUARIO, E.DESCRIPCION,
    SUM(D.DURACIONPORSEGUNDO*D.PRECIOPORSEGUNDO) "PAGO_DE_PUBLICIDAD"
FROM CUENTA A, VIDEO B, PUBLICIDAD_X_VIDEO C, PUBLICIDAD D,
    PRIVACIDAD E
WHERE A.IDCUENTA=B.IDCUENTA_PROPIETARIA 
    AND B.IDVIDEO=C.IDVIDEO AND C.IDPUBLICIDAD=D.IDPUBLICIDAD AND
    B.IDPRIVACIDAD=E.IDPRIVACIDAD --AND A.USUARIO NOT IN ('Abeta23_00')--AND SUM(D.DURACIONPORSEGUNDO*D.PRECIOPORSEGUNDO) in (2966)
    AND NOT EXISTS (
        SELECT *
        FROM ACCION X
        WHERE A.IDCUENTA=X.IDCUENTA AND X.FLAGLIKE=1 AND X.FLAGDISLIKE=1
    )
GROUP BY A.USUARIO, E.DESCRIPCION
HAVING SUM(D.DURACIONPORSEGUNDO*D.PRECIOPORSEGUNDO)>2000
ORDER BY 1;
/
--ACCESO A UNA VISTA
SELECT *
FROM VISTA_PAGOS_POR_PUBLICIDAD
/
--P2 F
CREATE INDEX INDICE_TITULO_VIDEO ON VIDEO (TITULO)
/
--ACCESO A UN INDICE
SELECT *
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'INDICE%';